In [11]:
import importlib
import sc_workflows.metadata as metadata

importlib.reload(metadata)

print(metadata.__file__)
print(dir(metadata))

/home/mhaioun/projects/single-cell-workflows/src/sc_workflows/metadata.py
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'ad', 'assess_longitudinal_coverage', 'pd', 'summarize_categories', 'summarize_cohort', 'summarize_metadata']

In [14]:
%load_ext autoreload
%autoreload 2

from sc_workflows.metadata import summarize_metadata, summarize_categories, summarize_cohort, assess_longitudinal_coverage

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [16]:
from sc_workflows.metadata import summarize_metadata
import scanpy as sc
adata = sc.read_h5ad("data/pbmc3k_filtered")
adata

AnnData object with n_obs × n_vars = 2681 × 13639
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'total_counts_mt', 'log1p_total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo'
    var: 'gene_ids', 'mt', 'ribo', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'n_cells'

In [17]:
summary = summarize_metadata(adata, axis="var")

display(summary)

,column,dtype,n_unique,n_missing,pct_missing,examples
0,gene_ids,object,13639,0,0.0,"[ENSG00000237683, ENSG00000228463, ENSG0000022..."
1,mt,bool,2,0,0.0,"[False, True]"
2,ribo,bool,2,0,0.0,"[False, True]"
3,n_cells_by_counts,int64,1194,0,0.0,"[9, 3, 5, 18, 258]"
4,mean_counts,float64,1449,0,0.0,"[0.0033333333333333335, 0.0011111111111111111,..."
5,log1p_mean_counts,float64,1449,0,0.0,"[0.0033277900926746693, 0.0011104942840271636,..."
6,pct_dropout_by_counts,float64,1194,0,0.0,"[99.66666666666667, 99.8888888888889, 99.81481..."
7,total_counts,float32,1449,0,0.0,"[9.0, 3.0, 5.0, 18.0, 288.0]"
8,log1p_total_counts,float32,1449,0,0.0,"[2.3025851, 1.3862944, 1.7917595, 2.944439, 5...."
9,n_cells,int64,1169,0,0.0,"[9, 3, 4, 18, 254]"

In [19]:
summary = summarize_categories(adata, "total_counts")

display(summary)

      total_counts  count
0           1991.0      6
1           1857.0      6
2           1870.0      6
3           2056.0      5
4           1864.0      5
...            ...    ...
1782        4348.0      1
1783        1191.0      1
1784        1152.0      1
1785        3034.0      1
1786        3918.0      1

[1787 rows x 2 columns]